package mps.sales.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AdditionalCharge;
  private ConceptPresentation props_Address;
  private ConceptPresentation props_CashSales;
  private ConceptPresentation props_Company;
  private ConceptPresentation props_CreditSales;
  private ConceptPresentation props_CustomDataType;
  private ConceptPresentation props_Customer;
  private ConceptPresentation props_Discount;
  private ConceptPresentation props_Item;
  private ConceptPresentation props_LineItem;
  private ConceptPresentation props_Location;
  private ConceptPresentation props_Transaction;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AdditionalCharge:
        if (props_AdditionalCharge == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AdditionalCharge");
          props_AdditionalCharge = cpb.create();
        }
        return props_AdditionalCharge;
      case LanguageConceptSwitch.Address:
        if (props_Address == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("merchant address");
          props_Address = cpb.create();
        }
        return props_Address;
      case LanguageConceptSwitch.CashSales:
        if (props_CashSales == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("cash sales");
          props_CashSales = cpb.create();
        }
        return props_CashSales;
      case LanguageConceptSwitch.Company:
        if (props_Company == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Company = cpb.create();
        }
        return props_Company;
      case LanguageConceptSwitch.CreditSales:
        if (props_CreditSales == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("credit sales");
          props_CreditSales = cpb.create();
        }
        return props_CreditSales;
      case LanguageConceptSwitch.CustomDataType:
        if (props_CustomDataType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("CustomDataType");
          props_CustomDataType = cpb.create();
        }
        return props_CustomDataType;
      case LanguageConceptSwitch.Customer:
        if (props_Customer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Customer = cpb.create();
        }
        return props_Customer;
      case LanguageConceptSwitch.Discount:
        if (props_Discount == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Discount");
          props_Discount = cpb.create();
        }
        return props_Discount;
      case LanguageConceptSwitch.Item:
        if (props_Item == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Item = cpb.create();
        }
        return props_Item;
      case LanguageConceptSwitch.LineItem:
        if (props_LineItem == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("LineItem");
          props_LineItem = cpb.create();
        }
        return props_LineItem;
      case LanguageConceptSwitch.Location:
        if (props_Location == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("location");
          props_Location = cpb.create();
        }
        return props_Location;
      case LanguageConceptSwitch.Transaction:
        if (props_Transaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Transaction = cpb.create();
        }
        return props_Transaction;
    }
    return null;
  }
}
