package mps.sales.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DataType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DataType() {
    super(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x15d7ae914edeb408L, "DataType", "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/1573918533905986568");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_VARCHAR_0 = new EnumerationDescriptor.MemberDescriptor("VARCHAR", "VARCHAR", 0x15d7ae914edeb409L, "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/1573918533905986569");
  private final EnumerationDescriptor.MemberDescriptor myMember_DATE_0 = new EnumerationDescriptor.MemberDescriptor("DATE", "DATE", 0x15d7ae914edeb40aL, "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/1573918533905986570");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x15d7ae914edeb408L, 0x15d7ae914edeb409L, 0x15d7ae914edeb40aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_VARCHAR_0, myMember_DATE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "VARCHAR":
        return myMember_VARCHAR_0;
      case "DATE":
        return myMember_DATE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
