package mps.sales.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TransactionType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TransactionType() {
    super(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x46012aa9887f7d23L, "TransactionType", "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/5044359965259562275");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CashSales_0 = new EnumerationDescriptor.MemberDescriptor("CashSales", "CASH SALES", 0x46012aa9887f7d24L, "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/5044359965259562276");
  private final EnumerationDescriptor.MemberDescriptor myMember_CreditSales_0 = new EnumerationDescriptor.MemberDescriptor("CreditSales", "CREDIT SALES", 0x46012aa9887f7d25L, "r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/5044359965259562277");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x46012aa9887f7d23L, 0x46012aa9887f7d24L, 0x46012aa9887f7d25L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CashSales_0, myMember_CreditSales_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CashSales":
        return myMember_CashSales_0;
      case "CreditSales":
        return myMember_CreditSales_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
