package mps.sales.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AdditionalCharge = 0;
  public static final int Address = 1;
  public static final int CashSales = 2;
  public static final int Company = 3;
  public static final int CreditSales = 4;
  public static final int CustomDataType = 5;
  public static final int Customer = 6;
  public static final int Discount = 7;
  public static final int Item = 8;
  public static final int LineItem = 9;
  public static final int Location = 10;
  public static final int Transaction = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L);
    builder.put(0x74c6770040fc31a2L, AdditionalCharge);
    builder.put(0x74c6770040fc31a9L, Address);
    builder.put(0x74c6770040fbc5e0L, CashSales);
    builder.put(0x74c6770040fbc5dcL, Company);
    builder.put(0x74c6770040fbc5e3L, CreditSales);
    builder.put(0x15d7ae914edeb406L, CustomDataType);
    builder.put(0x4f1b7084f993550L, Customer);
    builder.put(0x74c6770040fc319cL, Discount);
    builder.put(0x74c6770040fc12a0L, Item);
    builder.put(0x74c6770040fc016dL, LineItem);
    builder.put(0x4f1b7084f992afaL, Location);
    builder.put(0x74c6770040fbc5dfL, Transaction);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
