package mps.sales.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAdditionalCharge = createDescriptorForAdditionalCharge();
  /*package*/ final ConceptDescriptor myConceptAddress = createDescriptorForAddress();
  /*package*/ final ConceptDescriptor myConceptCashSales = createDescriptorForCashSales();
  /*package*/ final ConceptDescriptor myConceptCompany = createDescriptorForCompany();
  /*package*/ final ConceptDescriptor myConceptCreditSales = createDescriptorForCreditSales();
  /*package*/ final ConceptDescriptor myConceptCustomDataType = createDescriptorForCustomDataType();
  /*package*/ final ConceptDescriptor myConceptCustomer = createDescriptorForCustomer();
  /*package*/ final ConceptDescriptor myConceptDiscount = createDescriptorForDiscount();
  /*package*/ final ConceptDescriptor myConceptItem = createDescriptorForItem();
  /*package*/ final ConceptDescriptor myConceptLineItem = createDescriptorForLineItem();
  /*package*/ final ConceptDescriptor myConceptLocation = createDescriptorForLocation();
  /*package*/ final ConceptDescriptor myConceptTransaction = createDescriptorForTransaction();
  /*package*/ final EnumerationDescriptor myEnumerationDataType = new EnumerationDescriptor_DataType();
  /*package*/ final EnumerationDescriptor myEnumerationPaymentMethod = new EnumerationDescriptor_PaymentMethod();
  /*package*/ final EnumerationDescriptor myEnumerationTransactionType = new EnumerationDescriptor_TransactionType();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAdditionalCharge, myConceptAddress, myConceptCashSales, myConceptCompany, myConceptCreditSales, myConceptCustomDataType, myConceptCustomer, myConceptDiscount, myConceptItem, myConceptLineItem, myConceptLocation, myConceptTransaction);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AdditionalCharge:
        return myConceptAdditionalCharge;
      case LanguageConceptSwitch.Address:
        return myConceptAddress;
      case LanguageConceptSwitch.CashSales:
        return myConceptCashSales;
      case LanguageConceptSwitch.Company:
        return myConceptCompany;
      case LanguageConceptSwitch.CreditSales:
        return myConceptCreditSales;
      case LanguageConceptSwitch.CustomDataType:
        return myConceptCustomDataType;
      case LanguageConceptSwitch.Customer:
        return myConceptCustomer;
      case LanguageConceptSwitch.Discount:
        return myConceptDiscount;
      case LanguageConceptSwitch.Item:
        return myConceptItem;
      case LanguageConceptSwitch.LineItem:
        return myConceptLineItem;
      case LanguageConceptSwitch.Location:
        return myConceptLocation;
      case LanguageConceptSwitch.Transaction:
        return myConceptTransaction;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationDataType, myEnumerationPaymentMethod, myEnumerationTransactionType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAdditionalCharge() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "AdditionalCharge", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc31a2L);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762325410");
    b.version(2);
    b.property("amount", 0x74c6770040fc31a3L).type(PrimitiveTypeId.INTEGER).origin("8414543796762325411").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAddress() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Address", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc31a9L);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762325417");
    b.version(2);
    b.property("street", 0x4e2bd7337e60ddcdL).type(PrimitiveTypeId.STRING).origin("5632832375120518605").done();
    b.property("city", 0x4e2bd7337e5d8da9L).type(PrimitiveTypeId.STRING).origin("5632832375120301481").done();
    b.property("country", 0x4e2bd7337e60ddd0L).type(PrimitiveTypeId.STRING).origin("5632832375120518608").done();
    b.property("telephone", 0x4e2bd7337e60ddd4L).type(PrimitiveTypeId.STRING).origin("5632832375120518612").done();
    b.alias("merchant address");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCashSales() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "CashSales", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5e0L);
    b.class_(false, false, false);
    b.super_("mps.sales.structure.Transaction", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5dfL);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762297824");
    b.version(2);
    b.property("type", 0x74c6770040fbc5e1L).type(MetaIdFactory.dataTypeId(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x46012aa9887f7d23L)).origin("8414543796762297825").done();
    b.alias("cash sales");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCompany() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Company", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5dcL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762297820");
    b.version(2);
    b.property("codice", 0x74c6770040fd2b69L).type(PrimitiveTypeId.STRING).origin("8414543796762389353").done();
    b.aggregate("address", 0x4f1b7084f98bcb4L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc31a9L).optional(false).ordered(true).multiple(false).origin("356267091862011060").done();
    b.aggregate("customers", 0x15d7ae914eda31a8L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x4f1b7084f993550L).optional(true).ordered(true).multiple(true).origin("1573918533905691048").done();
    b.aggregate("transactions", 0x74c6770040fc31b2L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5dfL).optional(true).ordered(true).multiple(true).origin("8414543796762325426").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCreditSales() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "CreditSales", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5e3L);
    b.class_(false, false, false);
    b.super_("mps.sales.structure.Transaction", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5dfL);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762297827");
    b.version(2);
    b.property("type", 0x74c6770040fbc5e4L).type(PrimitiveTypeId.STRING).origin("8414543796762297828").done();
    b.property("cardHolder", 0x76e5265995c6ab3fL).type(PrimitiveTypeId.STRING).origin("8567296032349006655").done();
    b.property("cardNumber", 0x76e5265995c6ab42L).type(PrimitiveTypeId.STRING).origin("8567296032349006658").done();
    b.property("expiryDate", 0x76e5265995c6ab46L).type(PrimitiveTypeId.STRING).origin("8567296032349006662").done();
    b.alias("credit sales");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCustomDataType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "CustomDataType", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x15d7ae914edeb406L);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/1573918533905986566");
    b.version(2);
    b.property("dataType", 0x15d7ae914edeb40fL).type(MetaIdFactory.dataTypeId(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x15d7ae914edeb408L)).origin("1573918533905986575").done();
    b.property("length", 0x15d7ae914edeb411L).type(PrimitiveTypeId.INTEGER).origin("1573918533905986577").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCustomer() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Customer", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x4f1b7084f993550L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/356267091862041936");
    b.version(2);
    b.property("identityNumber", 0x15d7ae914edea0aaL).type(PrimitiveTypeId.STRING).origin("1573918533905981610").done();
    b.property("phoneNumber", 0x4f1b7084f993553L).type(PrimitiveTypeId.STRING).origin("356267091862041939").done();
    b.alias("customer");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiscount() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Discount", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc319cL);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762325404");
    b.version(2);
    b.property("amount", 0x74c6770040fc319dL).type(PrimitiveTypeId.INTEGER).origin("8414543796762325405").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Item", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc12a0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762317472");
    b.version(2);
    b.property("code", 0x74c6770040fc12a3L).type(PrimitiveTypeId.STRING).origin("8414543796762317475").done();
    b.property("description", 0x74c6770040fc12a5L).type(PrimitiveTypeId.STRING).origin("8414543796762317477").done();
    b.property("uom", 0x74c6770040fc12a8L).type(PrimitiveTypeId.STRING).origin("8414543796762317480").done();
    b.property("isActive", 0x74c6770040fc12acL).type(PrimitiveTypeId.BOOLEAN).origin("8414543796762317484").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLineItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "LineItem", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc016dL);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762313069");
    b.version(2);
    b.property("unitAmount", 0x74c6770040fc12b4L).type(PrimitiveTypeId.INTEGER).origin("8414543796762317492").done();
    b.property("quantity", 0x74c6770040fc12b6L).type(PrimitiveTypeId.INTEGER).origin("8414543796762317494").done();
    b.property("taxAmount", 0x74c6770040fc12b9L).type(PrimitiveTypeId.INTEGER).origin("8414543796762317497").done();
    b.property("totalAmount", 0x74c6770040fc12bdL).type(PrimitiveTypeId.INTEGER).origin("8414543796762317501").done();
    b.aggregate("item", 0x74c6770040fc12b2L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc12a0L).optional(false).ordered(true).multiple(false).origin("8414543796762317490").done();
    b.aggregate("discount", 0x74c6770040fc319fL).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc319cL).optional(true).ordered(true).multiple(false).origin("8414543796762325407").done();
    b.aggregate("additionalCharge", 0x74c6770040fc31a5L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc31a2L).optional(true).ordered(true).multiple(false).origin("8414543796762325413").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Location", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x4f1b7084f992afaL);
    b.class_(false, false, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/356267091862039290");
    b.version(2);
    b.property("latitude", 0x4f1b7084f992afbL).type(PrimitiveTypeId.STRING).origin("356267091862039291").done();
    b.property("longitude", 0x4f1b7084f992afdL).type(PrimitiveTypeId.STRING).origin("356267091862039293").done();
    b.alias("location");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTransaction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mps.sales", "Transaction", 0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fbc5dfL);
    b.class_(false, true, false);
    b.origin("r:1553ae46-2a2d-4948-9a23-2cea3299b2f3(mps.sales.structure)/8414543796762297823");
    b.version(2);
    b.property("transactionNumber", 0x74c6770040fc2694L).type(PrimitiveTypeId.STRING).origin("8414543796762322580").done();
    b.property("date", 0x74c6770040fc317aL).type(MetaIdFactory.dataTypeId(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x15d7ae914edeb408L)).origin("8414543796762325370").done();
    b.property("paymentMethod", 0x74c6770040fc318eL).type(MetaIdFactory.dataTypeId(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc317fL)).origin("8414543796762325390").done();
    b.property("grandTotal", 0x46012aa9887b152aL).type(PrimitiveTypeId.INTEGER).origin("5044359965259273514").done();
    b.associate("customer", 0x15d7ae914ee3c873L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x4f1b7084f993550L).optional(true).origin("1573918533906319475").done();
    b.aggregate("lineItem", 0x76e5265995c3fe90L).target(0xd2c82ff21fca47a9L, 0x9cebb491a324c870L, 0x74c6770040fc016dL).optional(false).ordered(true).multiple(true).origin("8567296032348831376").done();
    return b.create();
  }
}
